<?php

namespace NpDocumentTest\Model\Document\Service;

use NpDocument\Model\Document\DocumentClass\Document;
use NpDocument\Model\Document\Service\ToArray;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-03-05 at 14:09:15.
 */
class ToArrayTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ToArray
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $document = new Document;
        $this->object = new ToArray($document);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers NpDocument\Model\Document\Service\ToArray::extract
     */
    public function testExtract()
    {
        $res = $this->object->extract();
        $this->assertArrayHasKey('sections', $res);
        $this->assertArrayHasKey('links', $res);
    }

    /**
     * @covers NpDocument\Model\Document\Service\ToArray::docToArray
     */
    public function testDocToArray()
    {
        $document = new Document;
        $res = ToArray::docToArray($document);
        $this->assertArrayHasKey('sections', $res);
        $this->assertArrayHasKey('links', $res);
    }
}
