<?php
namespace NpDocumentTest\Model\Section\SectionClass;

use NpDocument\Model\Section\SectionClass\Section;
use NpDocumentTest\Model\Section\SectionClass\TestAsset\DataContainer;
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-08 at 22:06:20.
 */
class SectionTest extends AbstractSection
{
    /**
     * @var Section
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Section;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }


}
