<?php
namespace NpDocumentTest\Resource\Manager;

use NpDocument\Resource\Manager\Config as ConfigTestTarget;
use NpDocument\Resource\Manager\StandardManager;
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-03 at 11:45:16.
 */
class ConfigTest extends \PHPUnit_Framework_TestCase
{
    
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testConfigureCacheStorageToStandardManager()
    {
        $config =  array(
            'cache_storage' => array(
                'adapter' => array(
                    'name'    => 'filesystem',
                    'options' => array(
                        'dir_level' => 2,
                    ),
                ),
            ),
        );
        $configObject = new ConfigTestTarget($config);
        $standardManager = new StandardManager($configObject);
        $ref = new \ReflectionObject($standardManager);
        $method = $ref->getMethod('getStorage');
        $method->setAccessible(true);
        $this->assertInstanceOf('Zend\Cache\Storage\StorageInterface', $method->invoke($standardManager));
        
        //一応ね。
        unset($standardManager);
        $standardManager = new StandardManager;
        $configObject->configure($standardManager);
        $this->assertInstanceOf('Zend\Cache\Storage\StorageInterface', $method->invoke($standardManager));
    }
    /**
     * 
     * @depends testConfigureCacheStorageToStandardManager
     * @covers NpDocument\Resource\Manager\Config::configure
     */
    public function testConfigure()
    {
        $this->assertTrue(true, 'all dependent test is passed');
    }
}
