<?php
namespace NpDocumentTest\Model\Section;

use NpDocument\Model\Section\Config;
use NpDocument\Model\Section\SectionClass\Section;
use NpDocument\Model\Section\DataContainer;
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-10 at 13:46:14.
 */
class ConfigTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers NpDocument\Model\Section\Config::configure
     */
    public function testConfigure()
    {
        $section = $this->getMock('NpDocument\Model\Section\SectionInterface');
        $dataContainer = new DataContainer;
        $config = array(
            'data_container' => $dataContainer,
        );
        $oConfig = new Config($config);
        $section->expects($this->once())
                ->method('setDataContainer')
                ->with($this->equalTo($dataContainer));
        $oConfig->configure($section);
    }
    
    public function testDataContainerObjectConfigure()
    {
        $dataContainer = new DataContainer;
        $config = array(
            'data_container' => $dataContainer,
        );
        $oConfig = new Config($config);
        $section = new Section($oConfig);
        $this->assertSame($dataContainer, $section->getDataContainer());
        
    }
    
    public function testDataContainerClassNameConfigure()
    {
        $section = $this->getMock('NpDocument\Model\Section\SectionInterface');
        $config = array(
            'data_container' => 'NpDocument\Model\Section\DataContainer',
        );
        $oConfig = new Config($config);
        $section->expects($this->once())
                ->method('setDataContainer');
        $oConfig->configure($section);
    }
        
}
