<?php
namespace NpDocument\Model\Section;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-11 at 11:10:06.
 */
class DataContainerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DataContainer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DataContainer;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers NpDocument\Model\Section\DataContainer::setIdentifier
     * @todo   Implement testSetIdentifier().
     */
    public function testSetIdentifier()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers NpDocument\Model\Section\DataContainer::getIdentifier
     * @todo   Implement testGetIdentifier().
     */
    public function testGetIdentifier()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers NpDocument\Model\Section\DataContainer::generateGlobalSectionId
     */
    public function testGenerateGlobalSectionId()
    {
        $domainId = 3455663;
        $documentId = 334523;
        $sectionName = 'content';
        $sectionRev = 523;
        $globalSectionId = DataContainer::generateGlobalSectionId($domainId, $documentId, $sectionName, $sectionRev);
        //ルールが変わるとexpectedも変わる
        $this->assertEquals('34BAAF-051ABB-content.523', $globalSectionId);
    }

    /**
     * @covers NpDocument\Model\Section\DataContainer::setOriginate
     * @todo   Implement testSetOriginate().
     */
    public function testSetOriginate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers NpDocument\Model\Section\DataContainer::offsetSet
     * @todo   Implement testOffsetSet().
     */
    public function testOffsetSet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
