<?php
namespace NpDocumentTest\Model\Section;

use NpDocument\Model\Section\SectionClass\Section;
use NpDocument\Model\Section\SectionPluginManager;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-08 at 21:37:28.
 */
class SectionPluginManagerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var SectionPluginManager
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SectionPluginManager;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers NpDocument\Model\Section\SectionPluginManager::validatePlugin
     */
    public function testValidatePlugin()
    {
        $instance = new Section;
        $this->assertTrue($this->object->validatePlugin($instance));
        $notImplements = new \stdClass;
        $this->assertFalse($this->object->validatePlugin($notImplements));
    }
    
    /**
     * 
     * @expectedException Zend\ServiceManager\Exception\ServiceNotFoundException
     */
    public function testNoConfigGet()
    {
        $this->object->get('generic');
    }
    
    public function testByDiGet()
    {
        $config = array(
            'instance' => array(
                'NpDocument\Model\Section\SectionPluginManager' => array(
                    'parameters' => array(

                    ),
                    'injections' => array(
                        'setInvokableClass' => array(
                            array('name' => 'generic', 'invokableClass' => 'NpDocument\Model\Section\SectionClass\Section'),
                        ),
                    ),
                ),
            ),
        );
        $oConfig = new \Zend\Di\Config($config);
        $di = new \Zend\Di\Di;
        $oConfig->configure($di);
        
        $plugin = $di->get('NpDocument\Model\Section\SectionPluginManager');
        $this->assertInstanceOf('NpDocument\Model\Section\SectionPluginManager', $plugin);
        $instance = $plugin->get('generic');
        $this->assertInstanceOf('NpDocument\Model\Section\SectionClass\Section', $instance);
    }
}
