<?php
namespace NpDocument\Model\Section;

use NpDocument\Model\Section\Section;
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-08 at 22:06:20.
 */
class SectionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Section
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Section;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers NpDocument\Model\Section\Section::getIdentifier
     */
    public function testGetIdentifier()
    {
        $this->assertEquals(array('domain_id', 'document_id', 'section_name', 'section_rev'), $this->object->getIdentifier());
    }
}
